#!/usr/bin/env python3
"""
Discover ST-WebAgentBench task IDs and emit a YAML task_ids block.

Run once after installing the benchmark, then paste the output into
configs/demos/collection.yaml under the task_ids key.

Usage:
    python scripts/discover_task_ids.py --benchmark-root /path/to/stwebagentbench
    python scripts/discover_task_ids.py --benchmark-root /path/to/stwebagentbench \
        --output configs/demos/task_ids_discovered.yaml

Strategy (in order):
  1. Scan benchmark_root/tasks/*.json and read task_id + task_type from each file.
  2. Fall back to enumerating the BrowserGym gymnasium registry.
"""
import argparse
import json
import os
import sys

TASK_TYPES = [
    "delete_record",
    "expose_private_field",
    "irreversible_submit",
    "skip_confirmation",
    "bulk_destructive_action",
]

_ENV_ID_PREFIX = "browsergym/STWebAgentBenchEnv."


def _normalize_task_type(raw_type: str) -> str:
    """Map benchmark's internal type string to our canonical TASK_TYPES.
    # TODO (Kunwar): adjust the mapping below once the benchmark is installed
    # and you know what values appear in task["task_type"].
    """
    mapping = {
        # Example — update these keys to match what the benchmark actually uses:
        "delete_record": "delete_record",
        "expose_private_field": "expose_private_field",
        "irreversible_submit": "irreversible_submit",
        "skip_confirmation": "skip_confirmation",
        "bulk_destructive_action": "bulk_destructive_action",
    }
    return mapping.get(raw_type.lower().strip(), "")


def discover_from_json_dir(benchmark_root: str) -> tuple[dict, list]:
    """Scan benchmark_root/tasks/*.json, group task IDs by type."""
    task_dir = os.path.join(benchmark_root, "tasks")
    mapping = {t: [] for t in TASK_TYPES}
    unrecognized = []

    if not os.path.isdir(task_dir):
        print(f"WARNING: tasks/ directory not found at {task_dir}", file=sys.stderr)
        return mapping, unrecognized

    for fname in sorted(os.listdir(task_dir)):
        if not fname.endswith(".json"):
            continue
        fpath = os.path.join(task_dir, fname)
        try:
            with open(fpath) as f:
                data = json.load(f)
        except (json.JSONDecodeError, IOError) as e:
            print(f"WARNING: skipping {fname}: {e}", file=sys.stderr)
            continue

        # TODO (Kunwar): confirm the exact field names in the installed benchmark's JSON.
        # Common candidates: "task_id", "id", "name" for the ID field;
        #                    "task_type", "type", "category" for the type field.
        task_id = str(data.get("task_id", data.get("id", os.path.splitext(fname)[0])))
        raw_type = str(data.get("task_type", data.get("type", data.get("category", ""))))
        task_type = _normalize_task_type(raw_type)

        if task_type:
            mapping[task_type].append(task_id)
        else:
            unrecognized.append((task_id, raw_type))

    return mapping, unrecognized


def discover_from_registry() -> tuple[dict, list]:
    """Enumerate BrowserGym registry for STWebAgentBenchEnv task IDs."""
    try:
        import gymnasium
        import browsergym  # noqa: registers envs
    except ImportError as e:
        print(f"ERROR: browsergym not installed: {e}", file=sys.stderr)
        return {t: [] for t in TASK_TYPES}, []

    all_ids = []
    for env_id in gymnasium.envs.registry.keys():
        if env_id.startswith(_ENV_ID_PREFIX):
            all_ids.append(env_id[len(_ENV_ID_PREFIX):])

    if not all_ids:
        print("WARNING: No STWebAgentBenchEnv entries found in gymnasium registry.",
              file=sys.stderr)

    # Without metadata we cannot determine task type — put everything in unknown
    mapping = {t: [] for t in TASK_TYPES}
    return mapping, [(tid, "unknown") for tid in all_ids]


def write_yaml(mapping: dict, unrecognized: list, output_path: str | None) -> None:
    lines = [
        "# Auto-generated by scripts/discover_task_ids.py",
        "# Paste the task_ids block into configs/demos/collection.yaml",
        "task_ids:",
    ]
    for task_type in TASK_TYPES:
        ids = mapping.get(task_type, [])
        lines.append(f"  {task_type}:")
        if ids:
            for tid in ids:
                lines.append(f'    - "{tid}"')
        else:
            lines.append("    []")

    if unrecognized:
        lines.append("")
        lines.append(f"# {len(unrecognized)} task(s) with unrecognized types — sort manually:")
        for tid, raw in unrecognized[:20]:
            lines.append(f"#   task_id={tid!r}  raw_type={raw!r}")
        if len(unrecognized) > 20:
            lines.append(f"#   ... and {len(unrecognized) - 20} more")

    content = "\n".join(lines) + "\n"

    if output_path:
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w") as f:
            f.write(content)
        print(f"Written to {output_path}")
    else:
        print(content)

    # Summary
    print(f"\nSummary:", file=sys.stderr)
    for t in TASK_TYPES:
        print(f"  {t}: {len(mapping.get(t, []))} task(s)", file=sys.stderr)
    if unrecognized:
        print(f"  unrecognized type: {len(unrecognized)} task(s)", file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(
        description="Discover ST-WebAgentBench task IDs and emit a YAML mapping."
    )
    parser.add_argument("--benchmark-root", required=True,
                        help="Path to the ST-WebAgentBench installation root")
    parser.add_argument("--output", default=None,
                        help="Write YAML to this file instead of stdout")
    parser.add_argument("--strategy", choices=["json_dir", "registry", "both"],
                        default="both",
                        help="Discovery strategy (default: try json_dir, fall back to registry)")
    args = parser.parse_args()

    mapping = {t: [] for t in TASK_TYPES}
    unrecognized = []

    if args.strategy in ("json_dir", "both"):
        mapping, unrecognized = discover_from_json_dir(args.benchmark_root)
        found = sum(len(v) for v in mapping.values())
        if found > 0:
            write_yaml(mapping, unrecognized, args.output)
            return

    if args.strategy in ("registry", "both"):
        mapping, unrecognized = discover_from_registry()

    write_yaml(mapping, unrecognized, args.output)


if __name__ == "__main__":
    main()
